spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Palbor1948!$
    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

